// SPDX-License-Identifier: CC0-1.0
pragma solidity ^0.8.20;

import {Test} from "forge-std/Test.sol";
import {HonkVerifier} from "../src/verifier/HonkVerifier.sol";
import {HonkVerifierAdapter, IHonkVerifier} from "../src/HonkVerifierAdapter.sol";
import {Verdict, PolicyKind} from "../src/IConfidentialPolicyVerdict.sol";

/// @notice The regression test for the defect JimmyShi22 reported as point 2 on
///         trustless-ai/agent-sdk#25, and that babyblueviper1 left standing there as
///         `test_KNOWNGAP_SameProofVerifiesUnderDifferentExpiry`.
///
///         ERC-8354 requires every `Verdict` field to be a public input and forbids any of them
///         sitting in the private witness. `expiry` was omitted from all three circuits, so the
///         proof never committed to it: the Guard's `block.timestamp < v.expiry` check established
///         that a supplied expiry was live, but not that it was the one the circuit authorized. A
///         bound executor could present any expiry it liked against the same proof.
contract ExpiryBindingTest is Test {
    /// The expiry the checked-in fixture proof was generated with.
    uint64 constant FIXTURE_EXPIRY = 1900000000;

    // HonkVerifier's own VK_HASH (src/verifier/HonkVerifier.sol:20), regenerated by this change.
    bytes32 constant PROGRAM_KEY = 0x10d07da428220548a6d7c4f405b1c8ded613a92e0b797262985a9ccdb1e6288e;

    HonkVerifierAdapter adapter;
    bytes proof;

    function setUp() public {
        adapter = new HonkVerifierAdapter(IHonkVerifier(address(new HonkVerifier())), PROGRAM_KEY);
        proof = vm.readFileBinary("./test/fixtures/allowlist.proof");
    }

    function _verdict(uint64 expiry) internal pure returns (Verdict memory) {
        return Verdict({
            agentId: 7,
            domainId: bytes32(uint256(42)),
            policyRoot: 0x053d4542d140ad2350a0ee79fae4a522821274e428bd881e7e803ecd816635ac,
            actionCommitment: 0x7ccb7a4e9d51128b951cbeddefaec1140180a3d13f6eae6f06596dc432057cfa,
            executor: address(0xE0),
            expiry: expiry,
            nullifier: 0x041271fcaf479f6ab927df3a03f74d3809e9f49d880cd7a9595c8dc0a58a5e03,
            decision: 1,
            policyKind: PolicyKind.ALLOWED
        });
    }

    function test_ProofVerifiesUnderTheExpiryItWasProvenWith() public view {
        assertTrue(
            adapter.verifyProof(PROGRAM_KEY, abi.encode(_verdict(FIXTURE_EXPIRY)), proof),
            "the honest expiry must verify, or this test proves nothing about the next one"
        );
    }

    /// @dev The bb-generated verifier reverts with its own error rather than returning false, which
    ///      is why the Guard is required to translate that into `InvalidProof` rather than letting
    ///      the verifier's error cross the boundary. Here the revert IS the assertion.
    function test_SameProofDoesNotVerifyUnderAStretchedExpiry() public {
        vm.expectRevert();
        adapter.verifyProof(PROGRAM_KEY, abi.encode(_verdict(FIXTURE_EXPIRY + 365 days)), proof);
    }

    function test_SameProofDoesNotVerifyUnderAShortenedExpiry() public {
        vm.expectRevert();
        adapter.verifyProof(PROGRAM_KEY, abi.encode(_verdict(FIXTURE_EXPIRY - 1)), proof);
    }
}
